server:
  servlet:
    contextPath: /blc-kpi
  port: 8325
spring:
  application:
    name: BLC KPI Report V2
    api-key: 27fc2f8f489e4813a965114be60893d4
  profiles:
    active: dev
  security:
    user:
      name: blc-user
      password: Welike2kupo!
      roles: USER
  datasource:
    url: jdbc:postgresql://localhost:5432/KPI_Report
    username: PriceRequest
    password: welike2kupo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
generator:
  semaphorePermits: 1
  retryBackOffPeriod: 10000
  retryMaxAttempts: 3
google-analytics:
  credentials-file: /ga-blc-0327-001-e20fe1e70555.json
  metricNames:
    - newUsers
go-high-level:
  client-id: 66c62f6c2ffde35c5111ce74-m059sl9k
  client-secret: 79854777-8ce0-4ea5-905f-4dea5074cc09
microsoft-clarity:
  base-url: https://www.clarity.ms/export-data/api/v1/project-live-insights
  num-of-days: 1
  dimensions:
    - URL
    - Device
  metrics:
    - ScrollDepth
    - EngagementTime
    - Traffic
kpi-report:
  ghlLocationIds:
    - KzkNJDWtvtee1quKjT8z # Bathrooms of Charleston
    - OW9jB57PFkL4sYankoog # S. Brown Construction Co.
    - OblTdbpiAyFSEVBL5Qfb # Triple Crown Homes
    - Tkmgh0RupoHFq0iCJosQ # Kashi Custom Homes
    - lWZrtj8byFZrUI9Cg2eX # Regency Homes
    - QUqcw0nLwPlwL1bZbAY3 # Morning Star Builders
