logging:
  level:
    root: INFO
  file-path: ../logs/kpi-reports/application-dev.log
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/KPI_Report
    username: PriceRequest
    password: welike2kupo
  mail:
    account:
      username: ian@builderleadconverter.com
      password: bslp hgxo phlj jdrg
    report-notification:
      recipients: ian@builderleadconverter.com,ianculanag@gmail.com