logging:
  level:
    root: INFO
server:
  servlet:
    contextPath: /blc-kpi
  port: 8325
spring:
  application:
    name: BLC KPI Report V2
    api-key: 27fc2f8f489e4813a965114be60893d4
  profiles:
    active: dev
  security:
    user:
      name: blc-user
      password: Welike2kupo!
      roles: USER
  datasource:
    url: jdbc:postgresql://localhost:5432/KPI_Report
    username: PriceRequest
    password: welike2kupo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    account:
      username: ian@builderleadconverter.com
      password: bslp hgxo phlj jdrg
    report-notification:
      recipients: ian@builderleadconverter.com,ianculanag@gmail.com
generator:
  semaphorePermits: 1
  retryBackOffPeriod: 30000
  retryMaxAttempts: 3
google-analytics:
  credentials-file: /ga-blc-0327-001-94fee12f04e8.json
  metricNames:
    - newUsers
    - averageSessionDuration
go-high-level:
  client-id: 66c62f6c2ffde35c5111ce74-m0lfshmu
  client-secret: f6372543-8118-4075-bbf9-24e973be0083
microsoft-clarity:
  base-url: https://www.clarity.ms/export-data/api/v1/project-live-insights
  num-of-days: 1
  dimensions:
    - URL
    - Device
  metrics:
    - ScrollDepth
    - EngagementTime
    - Traffic
kpi-report:
  ghlLocationIds:
    - t9hgdtElt0k1eEV2ralH
    - lE8DaY6mjkzIl3c7BmJf
    - BM6Uv86rhUcGpHDfNhIH
    - KzkNJDWtvtee1quKjT8z
    - FFcZhvJ6zdr4uQ76zc3k
    - 7pnhIDGXfDSqzMApYx9E
    - eyRMYzEpko9u4UlRYQEX
    - cyPiPQ1BiR8c0uLW7FjW
    - 4PLuaLLR7nxLr13dJWYo
    - Jqib3b8Px9hLqG2uPf90
    - oZmYcqNorvGyqM55aTi4
    - ppWmGZaczichea69P6zd
    - ASFvVIJmDvgmgC2HDbhN
    - KpWl4SIKNQgSzpAlrNaA
    - Tkmgh0RupoHFq0iCJosQ
    - QUqcw0nLwPlwL1bZbAY3
    - 9uSMOk8qWSKm12AxKBfg
    - 4yHvxQVBc35P4UAK0G98
    - ln0KsmHfn0YHB33ApoVV
    - zPZuToYS3M4R78Td9of0
    - lWZrtj8byFZrUI9Cg2eX
    - OW9jB57PFkL4sYankoog
    - OblTdbpiAyFSEVBL5Qfb
    - 5vfwcu3zxHUdHybkGmw5
    - iNj0Dg3P9YQlAXbz6b3R
    - RsP2iFiH92QXbGkV1scN
    - WikBDTbhq0XkMkVPLTg2
    - 0aLEDqje2UIjN1JZOV9I
    - udaMDd4CWtzbVrXBVJhV
openai:
  api:
    project-id: proj_lQNqnv2XyC68K6ofi7Xp2NUO
    base-url: https://api.openai.com/v1
    model: gpt-4o
    max-tokens: 4096
